export const HOST_DOMAIN = "hblab.vn";
export const SET_AUTH_GSUITE = "SET_AUTH_GSUITE";
export const SET_AUTH_GSUITE_ERROR = "SET_AUTH_GSUITE_ERROR";
export const SET_AUTH_NORMAL = "SET_AUTH_NORMAL";

export const SET_REQUEST = "SET_REQUEST";
export const REQUEST_LOADED_SUCCESS = "REQUEST_LOADED_SUCCESS";
export const REQUEST_LOADED_FAIL = "REQUEST_LOADED_FAIL";
export const DETAIL_REQUEST_SUCCESS = "DETAIL_REQUEST_SUCCESS";
export const DETAIL_REQUEST_FAIL = "DETAIL_REQUEST_FAIL";
export const EDIT_REQUEST = "EDIT_REQUEST";
export const GET_COMMENTS = "GET_COMMENTS";
export const CREATE_COMMENT= "CREATE_COMMENT";

export const SET_ALL_USERS = "SET_ALL_USERS";
export const SET_ALL_USERS_WITH_ADMIN = "SET_ALL_USERS_WITH_ADMIN";
export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
